// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using u20530545_HW01_API.Data;

#nullable disable

namespace u20530545_HW01_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240329192906_Courses")]
    partial class Courses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("u20530545_HW01_API.Models.Course", b =>
                {
                    b.Property<int>("courseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("courseId"));

                    b.Property<string>("courseDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("courseDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("courseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("courseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            courseId = 1,
                            courseDescription = "Year 1 , Semester 1 , Academic Information Management",
                            courseDuration = "Semester",
                            courseName = "AIM 101"
                        },
                        new
                        {
                            courseId = 2,
                            courseDescription = "Accounting Principles",
                            courseDuration = "Semester 1",
                            courseName = "FRK 113"
                        },
                        new
                        {
                            courseId = 3,
                            courseDescription = "Introduction to API's",
                            courseDuration = "Year",
                            courseName = "INF 200"
                        },
                        new
                        {
                            courseId = 4,
                            courseDescription = "Advanced Programming",
                            courseDuration = "Year",
                            courseName = "INF 345"
                        },
                        new
                        {
                            courseId = 5,
                            courseDescription = "Taxonomies",
                            courseDuration = "Year",
                            courseName = "INF 200"
                        },
                        new
                        {
                            courseId = 6,
                            courseDescription = "Year 2 , Semester 1 , Academic Information Management",
                            courseDuration = "Semester",
                            courseName = "INF 345"
                        },
                        new
                        {
                            courseId = 7,
                            courseDescription = "Year 3. Project",
                            courseDuration = "Year",
                            courseName = "INF 370"
                        },
                        new
                        {
                            courseId = 8,
                            courseDescription = "Introduction to API's",
                            courseDuration = "Semester 1",
                            courseName = "INF 354"
                        },
                        new
                        {
                            courseId = 9,
                            courseDescription = "Year 3 , Semester 2 , IT Trends",
                            courseDuration = "Semester",
                            courseName = "INF 324"
                        },
                        new
                        {
                            courseId = 10,
                            courseDescription = "Year 3 , Semester 1 . Programming Management",
                            courseDuration = "Semester",
                            courseName = "INF 315"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
